In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("cs-training.csv")

In [3]:
data

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149995,149996,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,149997,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149997,149998,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149998,149999,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149999,150000,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [ ]:
list(data.columns)

['SeriousDlqin2yrs',
 'RevolvingUtilizationOfUnsecuredLines',
 'age',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'DebtRatio',
 'MonthlyIncome',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfDependents']

In [9]:
list(data.columns)

['Unnamed: 0',
 'SeriousDlqin2yrs',
 'RevolvingUtilizationOfUnsecuredLines',
 'age',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'DebtRatio',
 'MonthlyIncome',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfDependents']

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [20]:
ty = data["NumberOfDependents"].dtype

In [22]:
str(ty)

'float64'

In [23]:
data.duplicated().sum()

0

# data quality analysis

In [3]:
data.shape

(150000, 12)

In [4]:
data.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [4]:
data.drop("Unnamed: 0",axis=1,inplace=True)

In [6]:
data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [7]:
data.isnull().sum()

SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

In [8]:
data[data.duplicated()]

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1669,0,1.0,29,0,0.0,NaN,0,0,0,0,0.0
7823,0,1.0,29,0,0.0,NaN,0,0,0,0,0.0
7920,0,1.0,22,0,0.0,820.0,1,0,0,0,0.0
8840,0,1.0,23,0,0.0,820.0,1,0,0,0,0.0
10869,0,1.0,73,0,0.0,NaN,2,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149139,0,0.0,77,0,0.0,NaN,2,0,0,0,0.0
149431,0,1.0,25,0,0.0,NaN,1,0,0,0,NaN
149472,0,1.0,84,0,0.0,NaN,1,0,0,0,0.0
149769,0,1.0,23,98,0.0,NaN,0,98,0,98,NaN
149993,0,1.0,22,0,0.0,820.0,1,0,0,0,0.0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [10]:
# nan values are present 
# duplicate values are present
# no datatype mismatch

# descriptive statistics

In [11]:
data.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [12]:
data["RevolvingUtilizationOfUnsecuredLines"].describe()

count    150000.000000
mean          6.048438
std         249.755371
min           0.000000
25%           0.029867
50%           0.154181
75%           0.559046
max       50708.000000
Name: RevolvingUtilizationOfUnsecuredLines, dtype: float64

In [13]:
data[data["RevolvingUtilizationOfUnsecuredLines"]>1]

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
162,1,1.046279,47,1,1.104301,5416.0,6,0,2,0,1.0
191,0,1.095083,53,5,0.536704,3500.0,7,1,1,2,0.0
226,1,1.953488,38,0,0.153500,3556.0,5,0,0,0,2.0
251,1,1.048211,58,7,0.151957,3500.0,12,0,0,0,0.0
293,0,2340.000000,45,0,0.339333,8333.0,7,0,2,0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
149939,0,1.049900,26,0,0.073220,6500.0,6,0,0,1,0.0
149955,1,1.135552,41,2,0.845887,7500.0,12,0,4,1,0.0
149962,0,1.005733,48,0,0.248896,2944.0,4,3,0,0,1.0
149964,0,1.010934,63,0,0.608211,6015.0,8,0,1,0,0.0
149973,0,1.026395,44,0,0.494819,5500.0,7,0,1,0,1.0

In [14]:
data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [5]:
data

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149995,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149997,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149998,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149999,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [11]:
dic = data.to_dict(orient='records')

In [13]:
dic[1]

{'SeriousDlqin2yrs': 0,
 'RevolvingUtilizationOfUnsecuredLines': 0.957151019,
 'age': 40,
 'NumberOfTime30-59DaysPastDueNotWorse': 0,
 'DebtRatio': 0.121876201,
 'MonthlyIncome': 2600.0,
 'NumberOfOpenCreditLinesAndLoans': 4,
 'NumberOfTimes90DaysLate': 0,
 'NumberRealEstateLoansOrLines': 0,
 'NumberOfTime60-89DaysPastDueNotWorse': 0,
 'NumberOfDependents': 1.0}

In [3]:
import pymongo

In [ ]:
# client = pymongo.MongoClient(mongodb_server)
# db = client["credit-risk-customers"]
# collection = db["cutomers"]
# # collection.insert_many(dic)

In [15]:
row = collection.find()

In [19]:
next(row)

{'_id': ObjectId('6a58774ce723bf5d91382fb3'),
 'SeriousDlqin2yrs': 0,
 'RevolvingUtilizationOfUnsecuredLines': 0.08040863,
 'age': 53,
 'NumberOfTime30-59DaysPastDueNotWorse': 0,
 'DebtRatio': 0.896689625,
 'MonthlyIncome': 4500.0,
 'NumberOfOpenCreditLinesAndLoans': 23,
 'NumberOfTimes90DaysLate': 0,
 'NumberRealEstateLoansOrLines': 2,
 'NumberOfTime60-89DaysPastDueNotWorse': 0,
 'NumberOfDependents': 0.0}

In [2]:
import boto3

In [4]:
s = boto3.client("s3",
                 aws_access_key_id=AWS_ACCESS_KEY_ID,
                 aws_secret_access_key=AWS_SECERET_ACCESS_KEY_ID)

In [7]:
s

In [5]:
response = s.list_buckets()

In [6]:
response

{'ResponseMetadata': {'RequestId': 'BYFFQ1XZ44G0AT2R',
  'HostId': 'RSWk5zPG7ovfH0xLi1X6Ohskgyg2vNBic4TBRp199BgySTa6OSORJxI1/J4lfw8NpkVc3ZaMpztho4dO4YuI2S/voYpApBgi',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'RSWk5zPG7ovfH0xLi1X6Ohskgyg2vNBic4TBRp199BgySTa6OSORJxI1/J4lfw8NpkVc3ZaMpztho4dO4YuI2S/voYpApBgi',
   'x-amz-request-id': 'BYFFQ1XZ44G0AT2R',
   'date': 'Sun, 19 Jul 2026 03:56:13 GMT',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'churnprojectbucket',
   'CreationDate': datetime.datetime(2026, 6, 6, 6, 40, 39, tzinfo=tzutc())},
  {'Name': 'visaprojectbucket',
   'CreationDate': datetime.datetime(2026, 5, 18, 7, 13, 20, tzinfo=tzutc())}],
 'Owner': {'ID': 'd683345c1b8fbbc864f9449fc07735fd167043d4c55db5412d2b504596d0725b'}}

In [8]:
for bucket in response["Buckets"]:
    print(bucket["Name"],end=" ")
    print(bucket["CreationDate"])
    print()

churnprojectbucket 2026-06-06 06:40:39+00:00

visaprojectbucket 2026-05-18 07:13:20+00:00

In [11]:
s.create_bucket(Bucket="creditriskprojectbucket",CreateBucketConfiguration={"LocationConstraint":region})

{'ResponseMetadata': {'RequestId': '8A5NVCZJTSHFEZTV',
  'HostId': 'ebLJs3iqUskSS8rMAVjRqOCrzrukhUunmJBDJwWmjo3UygY4a3yYBjp1R9byRUir/p8XpexKjyvWmscVCHxqGRPFts6eGIYm',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'ebLJs3iqUskSS8rMAVjRqOCrzrukhUunmJBDJwWmjo3UygY4a3yYBjp1R9byRUir/p8XpexKjyvWmscVCHxqGRPFts6eGIYm',
   'x-amz-request-id': '8A5NVCZJTSHFEZTV',
   'date': 'Sun, 19 Jul 2026 04:11:14 GMT',
   'location': 'http://creditriskprojectbucket.s3.amazonaws.com/',
   'x-amz-bucket-arn': 'arn:aws:s3:::creditriskprojectbucket',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Location': 'http://creditriskprojectbucket.s3.amazonaws.com/'}

In [12]:
buckets = s.list_buckets()

In [13]:
buckets

{'ResponseMetadata': {'RequestId': 'KH3W44JWT7GV7A0T',
  'HostId': '+ksDhGEM7/h/64eY3huZxjH6eei0qJVa6hnqcR2nLbMX9X1J6YPzqTppKfaZjNknxZqsN5dAi0C7XbvnWP7BNWHpTX7yXwmU',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': '+ksDhGEM7/h/64eY3huZxjH6eei0qJVa6hnqcR2nLbMX9X1J6YPzqTppKfaZjNknxZqsN5dAi0C7XbvnWP7BNWHpTX7yXwmU',
   'x-amz-request-id': 'KH3W44JWT7GV7A0T',
   'date': 'Sun, 19 Jul 2026 04:12:29 GMT',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'churnprojectbucket',
   'CreationDate': datetime.datetime(2026, 6, 6, 6, 40, 39, tzinfo=tzutc())},
  {'Name': 'creditriskprojectbucket',
   'CreationDate': datetime.datetime(2026, 7, 19, 4, 11, 14, tzinfo=tzutc())},
  {'Name': 'visaprojectbucket',
   'CreationDate': datetime.datetime(2026, 5, 18, 7, 13, 20, tzinfo=tzutc())}],
 'Owner': {'ID': 'd683345c1b8fbbc864f9449fc07735fd167043d4c55db5412d2b504596d0725b'}}

In [14]:
for bucket in buckets["Buckets"]:
    print(bucket["Name"])

churnprojectbucket
creditriskprojectbucket
visaprojectbucket

In [15]:
s.upload_file("test.txt","creditriskprojectbucket","text")

In [16]:
objects = s.list_objects_v2(Bucket="creditriskprojectbucket")

In [17]:
objects

{'ResponseMetadata': {'RequestId': 'M0X4D885JNJ2A36M',
  'HostId': 'fmYrI5EYuO8a1ybbHs2F05TxTTzMEJjyXw/d9hqVy8jZa/erWgnQWpnst0+c+STTxIc5xmkOwlGphudj0hJ4q12zNsZvl2+u',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'fmYrI5EYuO8a1ybbHs2F05TxTTzMEJjyXw/d9hqVy8jZa/erWgnQWpnst0+c+STTxIc5xmkOwlGphudj0hJ4q12zNsZvl2+u',
   'x-amz-request-id': 'M0X4D885JNJ2A36M',
   'date': 'Sun, 19 Jul 2026 04:17:39 GMT',
   'x-amz-bucket-region': 'eu-north-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'IsTruncated': False,
 'Contents': [{'Key': 'text',
   'LastModified': datetime.datetime(2026, 7, 19, 4, 16, 31, tzinfo=tzutc()),
   'ETag': '"21158172e961c9cca67a31013ca7783a"',
   'ChecksumAlgorithm': ['CRC64NVME'],
   'Size': 20,
   'StorageClass': 'STANDARD'}],
 'Name': 'creditriskprojectbucket',
 'Prefix': '',
 'MaxKeys': 1000,
 'EncodingType': 'url',
 'KeyCount': 1}

In [24]:
objects["Contents"][0]["Key"]

'text'

In [25]:
s.download_file("creditriskprojectbucket","text","aws_text")

In [26]:
res = s.head_object(Bucket = "creditriskprojectbucket",
                    Key = "text")

In [27]:
res

{'ResponseMetadata': {'RequestId': '34PV4X35N3B7ES44',
  'HostId': 'msLRpcUL7fQkEKxvQnCsbxuPL6DXIa179yJEe3JBotottRUW/VKFelK+fEC/whzxNFxlbLNljQRec6OE5zjPlnAGu9iT8JgT',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'msLRpcUL7fQkEKxvQnCsbxuPL6DXIa179yJEe3JBotottRUW/VKFelK+fEC/whzxNFxlbLNljQRec6OE5zjPlnAGu9iT8JgT',
   'x-amz-request-id': '34PV4X35N3B7ES44',
   'date': 'Sun, 19 Jul 2026 04:22:53 GMT',
   'last-modified': 'Sun, 19 Jul 2026 04:16:31 GMT',
   'etag': '"21158172e961c9cca67a31013ca7783a"',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'binary/octet-stream',
   'content-length': '20',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 7, 19, 4, 16, 31, tzinfo=tzutc()),
 'ContentLength': 20,
 'ETag': '"21158172e961c9cca67a31013ca7783a"',
 'ContentType': 'binary/octet-stream',
 'ServerSideEncryption': 'AES256',
 'Metadata': {}}

In [28]:
s.delete_object(Bucket = "creditriskprojectbucket",
                Key = "text")

{'ResponseMetadata': {'RequestId': 'JMPPZEKAS575RXNN',
  'HostId': '2e8+vFmfi8epnvhxgtf+QCjLyLeRcTK+hCBWD5HajytC+k32KOJpLNRoFUjenLFUTIIF7ZiyGBXG0FO54ZJhgW9O4m3vHUkv',
  'HTTPStatusCode': 204,
  'HTTPHeaders': {'x-amz-id-2': '2e8+vFmfi8epnvhxgtf+QCjLyLeRcTK+hCBWD5HajytC+k32KOJpLNRoFUjenLFUTIIF7ZiyGBXG0FO54ZJhgW9O4m3vHUkv',
   'x-amz-request-id': 'JMPPZEKAS575RXNN',
   'date': 'Sun, 19 Jul 2026 04:24:09 GMT',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}

In [31]:
churn_objects = s.list_objects_v2(Bucket = "churnprojectbucket", Prefix = "model.joblib" )

In [32]:
churn_objects

{'ResponseMetadata': {'RequestId': '5JHJHQ09J9B83RQE',
  'HostId': 'WBO3lXQJCqsGJgzk+blrq6z3GkM+9yH9HSR8BczTwYAWque6lYEhTqQ1IprrmoLiJ5f4ZEuEluEieuK4wjvDt6RPwTxhxR7J',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'WBO3lXQJCqsGJgzk+blrq6z3GkM+9yH9HSR8BczTwYAWque6lYEhTqQ1IprrmoLiJ5f4ZEuEluEieuK4wjvDt6RPwTxhxR7J',
   'x-amz-request-id': '5JHJHQ09J9B83RQE',
   'date': 'Sun, 19 Jul 2026 05:30:26 GMT',
   'x-amz-bucket-region': 'eu-north-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'IsTruncated': False,
 'Contents': [{'Key': 'model.joblib',
   'LastModified': datetime.datetime(2026, 6, 8, 4, 50, 38, tzinfo=tzutc()),
   'ETag': '"92c577d60407f8ff6db7d7ae87ec6bcb"',
   'ChecksumAlgorithm': ['CRC64NVME'],
   'Size': 940902,
   'StorageClass': 'STANDARD'}],
 'Name': 'churnprojectbucket',
 'Prefix': 'model.joblib',
 'MaxKeys': 1000,
 'EncodingType': 'url',
 'KeyCount': 1}

In [40]:
obj = churn_objects["Contents"][0]

In [42]:
obj

{'Key': 'model.joblib',
 'LastModified': datetime.datetime(2026, 6, 8, 4, 50, 38, tzinfo=tzutc()),
 'ETag': '"92c577d60407f8ff6db7d7ae87ec6bcb"',
 'ChecksumAlgorithm': ['CRC64NVME'],
 'Size': 940902,
 'StorageClass': 'STANDARD'}

In [55]:
object_information = s.get_object(Bucket = "churnprojectbucket",
                                  Key = "model.joblib")

In [56]:
object_information

{'ResponseMetadata': {'RequestId': '9TJ1NZX81HNT0RTQ',
  'HostId': 'y1dvWZENfgj/jxtrt5QIxAsta7W73zw0IbU4roEKrIN0ZlsQIUBQjjdzCKYTvutBi9ztF/IVRNPBsj+d9BI/h28jkOPaWaK1',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'y1dvWZENfgj/jxtrt5QIxAsta7W73zw0IbU4roEKrIN0ZlsQIUBQjjdzCKYTvutBi9ztF/IVRNPBsj+d9BI/h28jkOPaWaK1',
   'x-amz-request-id': '9TJ1NZX81HNT0RTQ',
   'date': 'Sun, 19 Jul 2026 05:47:30 GMT',
   'last-modified': 'Mon, 08 Jun 2026 04:50:38 GMT',
   'etag': '"92c577d60407f8ff6db7d7ae87ec6bcb"',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'binary/octet-stream',
   'content-length': '940902',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 6, 8, 4, 50, 38, tzinfo=tzutc()),
 'ContentLength': 940902,
 'ETag': '"92c577d60407f8ff6db7d7ae87ec6bcb"',
 'ContentType': 'binary/octet-stream',
 'ServerSideEncryption': 'AES256',
 'Metadata': {},
 'Body': <botocore.response.StreamingBody at 0x2134919e500>}

In [57]:
from io import BytesIO

In [58]:
bytes = object_information["Body"].read()

In [60]:
stream = BytesIO(bytes)

In [61]:
stream.read()

b'\x80\x04\x95\xe4\x07\x00\x00\x00\x00\x00\x00\x8c\x16churn.entity.estimator\x94\x8c\nchurnmodel\x94\x93\x94)\x81\x94}\x94(\x8c\x11preprocessing_obj\x94\x8c#sklearn.compose._column_transformer\x94\x8c\x11ColumnTransformer\x94\x93\x94)\x81\x94}\x94(\x8c\x0ctransformers\x94]\x94(\x8c\x11numerical_columns\x94\x8c\x10sklearn.pipeline\x94\x8c\x08Pipeline\x94\x93\x94)\x81\x94}\x94(\x8c\x05steps\x94]\x94(\x8c\x07imputer\x94\x8c\x14sklearn.impute._base\x94\x8c\rSimpleImputer\x94\x93\x94)\x81\x94}\x94(\x8c\x0emissing_values\x94G\x7f\xf8\x00\x00\x00\x00\x00\x00\x8c\radd_indicator\x94\x89\x8c\x13keep_empty_features\x94\x89\x8c\x08strategy\x94\x8c\x06median\x94\x8c\nfill_value\x94N\x8c\x07verbose\x94\x8c\ndeprecated\x94\x8c\x04copy\x94\x88\x8c\x10_sklearn_version\x94\x8c\x051.2.2\x94ub\x86\x94\x8c\x06scaler\x94\x8c\x1bsklearn.preprocessing._data\x94\x8c\x0eStandardScaler\x94\x93\x94)\x81\x94}\x94(\x8c\twith_mean\x94\x88\x8c\x08with_std\x94\x88h#\x88h$h%ub\x86\x94e\x8c\x06memory\x94N\x8c\x07verbose\x94\x89h$h%ub\x8c\x0cbox.box_list\x94\x8c\x07BoxList\x94\x93\x94)\x81\x94(\x8c\x0cTotalCharges\x94\x8c\x06tenure\x94\x8c\x0eMonthlyCharges\x94\x8c\rSeniorCitizen\x94e}\x94(\x8c\x0bbox_options\x94}\x94(\x8c\x0bdefault_box\x94\x89\x8c\x10default_box_attr\x94\x8c\x0ebox.config_box\x94\x8c\tConfigBox\x94\x93\x94\x8c\x1adefault_box_none_transform\x94\x88\x8c\x19default_box_create_on_get\x94\x88\x8c\x0econversion_box\x94\x88\x8c\x0fbox_safe_prefix\x94\x8c\x01x\x94\x8c\nfrozen_box\x94\x89\x8c\x10camel_killer_box\x94\x89\x8c\x11modify_tuples_box\x94\x89\x8c\x0ebox_duplicates\x94\x8c\x06ignore\x94\x8c\x10box_intact_types\x94)\x8c\nbox_recast\x94N\x8c\x08box_dots\x94\x89\x8c\rbox_namespace\x94\x8c\x11numerical_columns\x94\x85\x94\x8c\tbox_class\x94hAu\x8c\x0bbox_org_ref\x94\x8a\x06\x80\xf1aX\xb7\x02ub\x87\x94\x8c\x13categorical_columns\x94h\x10)\x81\x94}\x94(h\x13]\x94(\x8c\x06impute\x94h\x18)\x81\x94}\x94(h\x1bG\x7f\xf8\x00\x00\x00\x00\x00\x00h\x1c\x89h\x1d\x89h\x1e\x8c\rmost_frequent\x94h Nh!h"h#\x88h$h%ub\x86\x94h\'\x8c\x1fsklearn.preprocessing._encoders\x94\x8c\rOneHotEncoder\x94\x93\x94)\x81\x94}\x94(\x8c\ncategories\x94\x8c\x04auto\x94\x8c\x06sparse\x94h"\x8c\rsparse_output\x94\x88\x8c\x05dtype\x94\x8c\x05numpy\x94\x8c\x07float64\x94\x93\x94\x8c\x0ehandle_unknown\x94hK\x8c\x04drop\x94N\x8c\rmin_frequency\x94N\x8c\x0emax_categories\x94Nh$h%ub\x86\x94eh0Nh1\x89h$h%ubh4)\x81\x94(\x8c\x06gender\x94\x8c\x07Partner\x94\x8c\nDependents\x94\x8c\x0cPhoneService\x94\x8c\rMultipleLines\x94\x8c\x0fInternetService\x94\x8c\x0eOnlineSecurity\x94\x8c\x0cOnlineBackup\x94\x8c\x10DeviceProtection\x94\x8c\x0bTechSupport\x94\x8c\x0bStreamingTV\x94\x8c\x0fStreamingMovies\x94\x8c\x08Contract\x94\x8c\x10PaperlessBilling\x94\x8c\rPaymentMethod\x94e}\x94(h;}\x94(h=\x89h>hAhB\x88hC\x88hD\x88hEhFhG\x89hH\x89hI\x89hJhKhL)hMNhN\x89hO\x8c\x13categorical_columns\x94\x85\x94hRhAuhS\x8a\x06\x00\xf8\x03V\xb7\x02ub\x87\x94e\x8c\tremainder\x94hl\x8c\x10sparse_threshold\x94G?\xd3333333\x8c\x06n_jobs\x94N\x8c\x13transformer_weights\x94Nh1\x89\x8c\x19verbose_feature_names_out\x94\x88\x8c\x11feature_names_in_\x94\x8c\x13joblib.numpy_pickle\x94\x8c\x11NumpyArrayWrapper\x94\x93\x94)\x81\x94}\x94(\x8c\x08subclass\x94hh\x8c\x07ndarray\x94\x93\x94\x8c\x05shape\x94K\x13\x85\x94\x8c\x05order\x94\x8c\x01C\x94\x8c\x05dtype\x94hhh\x97\x93\x94\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01|\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94b\x8c\nallow_mmap\x94\x89\x8c\x1bnumpy_array_alignment_bytes\x94K\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x13\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x06\x00\x00\x00genderq\x12X\r\x00\x00\x00SeniorCitizenq\x13X\x07\x00\x00\x00Partnerq\x14X\n\x00\x00\x00Dependentsq\x15X\x06\x00\x00\x00tenureq\x16X\x0c\x00\x00\x00PhoneServiceq\x17X\r\x00\x00\x00MultipleLinesq\x18X\x0f\x00\x00\x00InternetServiceq\x19X\x0e\x00\x00\x00OnlineSecurityq\x1aX\x0c\x00\x00\x00OnlineBackupq\x1bX\x10\x00\x00\x00DeviceProtectionq\x1cX\x0b\x00\x00\x00TechSupportq\x1dX\x0b\x00\x00\x00StreamingTVq\x1eX\x0f\x00\x00\x00StreamingMoviesq\x1fX\x08\x00\x00\x00Contractq X\x10\x00\x00\x00PaperlessBillingq!X\r\x00\x00\x00PaymentMethodq"X\x0e\x00\x00\x00MonthlyChargesq#X\x0c\x00\x00\x00TotalChargesq$etq%b.\x95\x85\x01\x00\x00\x00\x00\x00\x00\x8c\x0en_features_in_\x94K\x13\x8c\x08_columns\x94]\x94(h5hpe\x8c\x1d_transformer_to_input_indices\x94}\x94(h\r]\x94(K\x12K\x04K\x11K\x01ehU]\x94(K\x00K\x02K\x03K\x05K\x06K\x07K\x08K\tK\nK\x0bK\x0cK\rK\x0eK\x0fK\x10e\x8c\tremainder\x94]\x94u\x8c\x0b_n_features\x94K\x13\x8c\n_remainder\x94h\xa7hlh\xa8\x87\x94\x8c\x0esparse_output_\x94\x89\x8c\x1b_name_to_fitted_passthrough\x94}\x94\x8c\rtransformers_\x94]\x94(h\rh\x10)\x81\x94}\x94(h\x13]\x94(h\x15h\x18)\x81\x94}\x94(h\x1bG\x7f\xf8\x00\x00\x00\x00\x00\x00h\x1c\x89h\x1d\x89h\x1eh\x1fh Nh!h"h#\x88\x8c\x11feature_names_in_\x94h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x04\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x0c\x00\x00\x00TotalChargesq\x12X\x06\x00\x00\x00tenureq\x13X\x0e\x00\x00\x00MonthlyChargesq\x14X\r\x00\x00\x00SeniorCitizenq\x15etq\x16b.\x95\x85\x00\x00\x00\x00\x00\x00\x00\x8c\x0en_features_in_\x94K\x04\x8c\n_fit_dtype\x94h\x98\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x8c\nindicator_\x94N\x8c\x0bstatistics_\x94h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x04\x85\x94h\x95h\x96h\x97h\xc2h\x9e\x88h\x9fK\x10ub\x02\xff\xffffff\xe6\xdb\x95@\x00\x00\x00\x00\x00\x00=@\xcd\xcc\xcc\xcc\xcc\x8cQ@\x00\x00\x00\x00\x00\x00\x00\x00\x95\xb2\x00\x00\x00\x00\x00\x00\x00h$h%ub\x86\x94h\'h*)\x81\x94}\x94(h-\x88h.\x88h#\x88h\xbeK\x04\x8c\x0fn_samples_seen_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x06scalar\x94\x93\x94h\x98\x8c\x02i8\x94\x89\x88\x87\x94R\x94(K\x03h\xc3NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94bC\x08\x9a\x14\x00\x00\x00\x00\x00\x00\x94\x86\x94R\x94\x8c\x05mean_\x94h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x04\x85\x94h\x95h\x96h\x97h\xc2h\x9e\x88h\x9fK\x10ub\x04\xff\xff\xff\xff\xaa\xc2\xd6K\xbe\xcd\xa1@r\x83\x8eT}I@@\xb0\xb6\xbfn\xb8\x1dP@\xf2\xcf*\xe3L\x88\xc4?\x95*\x00\x00\x00\x00\x00\x00\x00\x8c\x04var_\x94h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x04\x85\x94h\x95h\x96h\x97h\xc2h\x9e\x88h\x9fK\x10ub\x0c\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff%=AR|qSA\x10\x00\x1a_\x9d\xd5\x82@1\xe2f\xacYg\x8c@\xa7\x84\x9c\xb8#=\xc1?\x95,\x00\x00\x00\x00\x00\x00\x00\x8c\x06scale_\x94h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x04\x85\x94h\x95h\x96h\x97h\xc2h\x9e\x88h\x9fK\x10ub\n\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffp\xa5\xd4vH\xa3\xa1@\x89q\xcf\xeb\xcb\x8c8@F\x89H\xad\xf5%>@\x82\xff(\x99\xb0|\xd7?\x95\x98\x00\x00\x00\x00\x00\x00\x00h$h%ub\x86\x94eh0Nh1\x89h$h%ubh5\x87\x94hUh\x10)\x81\x94}\x94(h\x13]\x94(hYh\x18)\x81\x94}\x94(h\x1bG\x7f\xf8\x00\x00\x00\x00\x00\x00h\x1c\x89h\x1d\x89h\x1eh\\h Nh!h"h#\x88h\xb6h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x0f\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x0f\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x06\x00\x00\x00genderq\x12X\x07\x00\x00\x00Partnerq\x13X\n\x00\x00\x00Dependentsq\x14X\x0c\x00\x00\x00PhoneServiceq\x15X\r\x00\x00\x00MultipleLinesq\x16X\x0f\x00\x00\x00InternetServiceq\x17X\x0e\x00\x00\x00OnlineSecurityq\x18X\x0c\x00\x00\x00OnlineBackupq\x19X\x10\x00\x00\x00DeviceProtectionq\x1aX\x0b\x00\x00\x00TechSupportq\x1bX\x0b\x00\x00\x00StreamingTVq\x1cX\x0f\x00\x00\x00StreamingMoviesq\x1dX\x08\x00\x00\x00Contractq\x1eX\x10\x00\x00\x00PaperlessBillingq\x1fX\r\x00\x00\x00PaymentMethodq etq!b.\x95t\x00\x00\x00\x00\x00\x00\x00h\xbeK\x0fh\xbfh\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\xc5Nh\xc6h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x0f\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x0f\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x04\x00\x00\x00Maleq\x12X\x02\x00\x00\x00Noq\x13X\x02\x00\x00\x00Noq\x14X\x03\x00\x00\x00Yesq\x15X\x02\x00\x00\x00Noq\x16X\x0b\x00\x00\x00Fiber opticq\x17X\x02\x00\x00\x00Noq\x18X\x02\x00\x00\x00Noq\x19X\x02\x00\x00\x00Noq\x1aX\x02\x00\x00\x00Noq\x1bX\x02\x00\x00\x00Noq\x1cX\x02\x00\x00\x00Noq\x1dX\x0e\x00\x00\x00Month-to-monthq\x1eX\x03\x00\x00\x00Yesq\x1fX\x10\x00\x00\x00Electronic checkq etq!b.\x95\x9f\x00\x00\x00\x00\x00\x00\x00h$h%ub\x86\x94h\'h`)\x81\x94}\x94(hchdheh"hf\x88hghjhkhKhlNhmNhnN\x8c\x13_infrequent_enabled\x94\x89h\xbeK\x0f\x8c\x0bcategories_\x94]\x94(h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x02\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x06\x00\x00\x00Femaleq\x12X\x04\x00\x00\x00Maleq\x13etq\x14b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x02\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x03\x00\x00\x00Yesq\x13etq\x14b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x02\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x03\x00\x00\x00Yesq\x13etq\x14b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x02\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x03\x00\x00\x00Yesq\x13etq\x14b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x10\x00\x00\x00No phone serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x03\x00\x00\x00DSLq\x12X\x0b\x00\x00\x00Fiber opticq\x13X\x02\x00\x00\x00Noq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x13\x00\x00\x00No internet serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x13\x00\x00\x00No internet serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x13\x00\x00\x00No internet serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x13\x00\x00\x00No internet serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x13\x00\x00\x00No internet serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x13\x00\x00\x00No internet serviceq\x13X\x03\x00\x00\x00Yesq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x03\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x0e\x00\x00\x00Month-to-monthq\x12X\x08\x00\x00\x00One yearq\x13X\x08\x00\x00\x00Two yearq\x14etq\x15b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x02\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x02\x00\x00\x00Noq\x12X\x03\x00\x00\x00Yesq\x13etq\x14b.\x95E\x00\x00\x00\x00\x00\x00\x00h\x8d)\x81\x94}\x94(h\x90h\x92h\x93K\x04\x85\x94h\x95h\x96h\x97h\x98\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03h\x9cNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94bh\x9e\x89h\x9fK\x10ub\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00O8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00|q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?tq\x10b\x89]q\x11(X\x19\x00\x00\x00Bank transfer (automatic)q\x12X\x17\x00\x00\x00Credit card (automatic)q\x13X\x10\x00\x00\x00Electronic checkq\x14X\x0c\x00\x00\x00Mailed checkq\x15etq\x16b.\x95u\x02\x00\x00\x00\x00\x00\x00e\x8c\x18_drop_idx_after_grouping\x94N\x8c\tdrop_idx_\x94N\x8c\x10_n_features_outs\x94]\x94(K\x02K\x02K\x02K\x02K\x03K\x03K\x03K\x03K\x03K\x03K\x03K\x03K\x03K\x02K\x04eh$h%ub\x86\x94eh0Nh1\x89h$h%ubhp\x87\x94e\x8c\x0foutput_indices_\x94}\x94(h\r\x8c\x08builtin